import os
import json
from storage import RawStorage
from connectors import GmailConnector, WhatsAppConnector
from pipeline import GmailNormalizer, WhatsAppNormalizer, ConversationMerger

def main():
    print("--- ETL Normalization & Merging Manual Verification ---")
    
    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    
    # Paths
    raw_dir = os.path.join(project_root, 'raw')
    norm_dir = os.path.join(project_root, 'normalized')
    
    # 1. Initialize storage and connectors
    storage = RawStorage(base_dir=raw_dir)
    gmail_connector = GmailConnector(storage)
    whatsapp_connector = WhatsAppConnector(storage)
    
    # Mock files paths (generated by verify_ingestion.py or present in tests)
    mock_data_dir = os.path.join(project_root, 'tests', 'mock_data')
    mock_eml = os.path.join(mock_data_dir, 'sample_customer_email.eml')
    mock_wa = os.path.join(mock_data_dir, 'sample_whatsapp_chat.txt')
    
    if not os.path.exists(mock_eml) or not os.path.exists(mock_wa):
        print("Mock data files not found. Please run scripts/verify_ingestion.py first.")
        return
        
    # 2. Ingest
    print("\nIngesting raw data...")
    gmail_connector.ingest_eml_file(mock_eml)
    whatsapp_connector.ingest_chat_file(mock_wa)
    
    # 3. Normalize
    print("\nRunning normalizers...")
    gmail_raw = os.path.join(raw_dir, 'gmail')
    gmail_norm = os.path.join(norm_dir, 'gmail')
    gmail_normalizer = GmailNormalizer(
        raw_dir=gmail_raw, 
        normalized_dir=gmail_norm,
        company_domains=['shop.com']
    )
    gmail_normalizer.normalize_all()
    print("Gmail messages normalized.")
    
    whatsapp_raw = os.path.join(raw_dir, 'whatsapp')
    whatsapp_norm = os.path.join(norm_dir, 'whatsapp')
    whatsapp_normalizer = WhatsAppNormalizer(
        raw_dir=whatsapp_raw,
        normalized_dir=whatsapp_norm,
        agent_names=['Jane Doe']
    )
    whatsapp_normalizer.normalize_all()
    print("WhatsApp messages normalized.")
    
    # 4. Merge
    print("\nMerging into unified conversation records...")
    unified_dir = os.path.join(norm_dir, 'unified')
    merger = ConversationMerger(
        normalized_dirs=[gmail_norm, whatsapp_norm],
        unified_dir=unified_dir
    )
    unified_files = merger.merge_all()
    print(f"Merged {len(unified_files)} conversation(s) into unified records.")
    
    # 5. Display output unified conversation JSON
    print("\nUnified Conversation Details:")
    for path in unified_files:
        print(f"\n--- Unified file: {os.path.basename(path)} ---")
        with open(path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        print(json.dumps(data, indent=2, ensure_ascii=False))
        
    print("\nNormalization and Merging verification completed successfully!")

if __name__ == '__main__':
    main()
